#
# Copyright (C) 2024 Biomodal Ltd. All rights reserved.
#
#
# Copyright (C) 2023 Cambridge Epigenetix. All rights reserved.
#
name: Validate Terraform

on:
  pull_request:

jobs:
  run-terraform-validation:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          terraform_version: 1.5.4

      - name: terraform-validate
        run: |
          terraform init
          terraform fmt -write=false
          terraform validate
